# Base tests we can run on every commit/PR/etc
#
# Thanks to Nix caching, this will only run tests for components that
# have changed since previous successful runs.
name: Core Tests

on:
  # push:
  #   branches:
  #     - 'stage'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v15

      - name: Cachix
        uses: cachix/cachix-action@v10
        with:
          name: theta-idl
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      # - name: Build Theta (GHC 8.10.7)
      #   run: nix build .#theta_8107 -L

      # - name: Build Theta (GHC 9.0.2)
      #   run: nix build .#theta_902 -L

      # - name: Build Theta (GHC 9.2.5)
      #   run: nix build .#theta_925 -L

      # - name: Cross-Language Tests
      #   run: nix build .#test -L
